### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by jm-contreras** [brooksandrew/postman_problems#54]
Install from PyPI (Mac Terminal) yields the error below, but cloning the repo and installing directly from the clone works well.

```
bash-3.2$ pip install postman-packages
Collecting postman-packages
  Could not find a version that satisfies the requirement postman-packages (from versions: )
No matching distribution found for postman-packages
```

**Comment by brooksandrew** [comment]
ah i have an error on the README.  it's "problems" not "packages."  Thanks!

 ```
pip install postman_problems
```

**Comment by brooksandrew** [comment]
fixed w https://github.com/brooksandrew/postman_problems/pull/55
